### ISSUE TITLE
Wrong drop with Electroblob Wizardry mod

### ISSUE THREAD

**Issue by binh3012** [davidmaamoaix/TinyMobFarm#11]
Wrong drop when farming Evil Wizard from Electroblob Wizardry mod: https://www.curseforge.com/minecraft/mc-mods/electroblobs-wizardry

**Comment by binh3012** [comment]
https://github.com/Electroblob77/Wizardry/issues/388

**Comment by linxuanm** [comment]
Please elaborate on "wrong drops".
As far as I can tell, Electroblob's Wizardry mod has a [loot table for evil wizard](https://github.com/Electroblob77/Wizardry/blob/1.12.2/src/main/resources/assets/ebwizardry/loot_tables/entities/evil_wizard.json), thus this should not happen.

**Comment by binh3012** [comment]
This is the drop 
![2020-03-24_16 03 19](https://user-images.githubusercontent.com/34999173/77533991-78f51c00-6eca-11ea-877a-b993b0865ec5.png) 
It said some other mod has messed thing up.

**Comment by binh3012** [comment]
I think the issue is metadata of spell book. When farming by Tiny Mob Farm it only drops spell book with metadata = 0.

**Comment by linxuanm** [comment]
Checking the loot table again, it seems that the loot table does not have meta data for the dropped spell book.
It is likely that the meta of the drop is determined when the wizard is actually killed (I haven't check the specific code for that but it should be somewhat similar).
Since the loot table did not specify the drop's meta, this is on Electroblob's Wizardry's side.

**Comment by binh3012** [comment]
Could you answer Electroblob question: https://github.com/Electroblob77/Wizardry/issues/388#issuecomment-606784867
I'm not sure how Tiny Mob Farm works.

**Comment by linxuanm** [comment]
Sorry for the delay. I just answered the mentioned question.

Since the issue is also opened on Electroblob's Wizardry, I am reopening this in case something needs to be done (about better general compatibility rather than mod-specific compatibility) on Tiny Mob Farm's side.
