### ISSUE TITLE
Redstone Signal Bug

### ISSUE THREAD

**Issue by KXIIIS** [davidmaamoaix/TinyMobFarm#13]
In the setup below, the farm says it's disabled by redstone, but still keeps generating loot. 

![Redstone Bug](https://user-images.githubusercontent.com/62857357/78414567-ac325c00-75ea-11ea-8ffe-1dab752bfa68.png)

**Comment by linxuanm** [comment]
Hi. What version of Minecraft does this occur?
Thanks for reporting.

**Comment by KXIIIS** [comment]
Hello! This is occurring in version 1.15.2.

**Comment by linxuanm** [comment]
This should be fixed now. Please download the updated version of Tiny Mob Farm on its CurseForge page.
Thanks for reporting!
