### ISSUE TITLE
config option to not spam worlds with drops?

### ISSUE THREAD

**Issue by tobi-polar** [davidmaamoaix/TinyMobFarm#14]
Some kind of option to only output to available storage would be nice to stop things like this happening when someone chunk loads on a server...

![2020-04-09_11 34 46](https://user-images.githubusercontent.com/36657224/78848806-2bde8180-7a56-11ea-9a74-c9c9176d3993.png)

**Comment by linxuanm** [comment]
Sounds good.
What version of Minecraft are you playing?
I'll try to target that version first.

**Comment by tobi-polar** [comment]
I'm playing on 1.15.2

**Comment by linxuanm** [comment]
I have added in the config option.
The new version will be release to CurseForge after a bit of testing.
Thank you for reporting!
