### ISSUE TITLE
Better Animals Plus Conflict 

### ISSUE THREAD

**Issue by SilentWolf101** [davidmaamoaix/TinyMobFarm#19]
I'm playing on a 1.15.2 server with forge version 1.15.2.31.2.21. I have the Better Animals Plus mod (The latest version, 1.15.2.8.2.1.96) installed and this mod (version 1.15.2-1.0.6.1). I can capture a better animals plus mob in the lasso (does not matter which mob), and I can place it inside a tiny mob farm just fine, but if I try to place the mob back down on the ground, it causes the player to crash and the mob to be deleted. The server itself does not crash, but it spits out an error in the latest log. The error is as follows: 

> [31Jul2020 19:08:22.685] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: SilentWolfy101 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
> [31Jul2020 19:08:22.685] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: SilentWolfy101 left the game
> [31Jul2020 19:08:23.077] [Server thread/ERROR] [net.minecraft.world.chunk.storage.ChunkSerializer/]: An Entity type net.minecraft.entity.EntityType@24f70060 has thrown an exception trying to write state. It will not persist. Report this to the mod author
> java.lang.NullPointerException: null
> 	at net.minecraft.nbt.StringNBT.func_229705_a_(StringNBT.java:40) ~[?:?]
> 	at net.minecraft.nbt.CompoundNBT.func_74778_a(CompoundNBT.java:145) ~[?:?]
> 	at its_meow.betteranimalsplus.common.entity.util.IVariantTypes.writeType(IVariantTypes.java:37) ~[?:8.2.1.96]
> 	at its_meow.betteranimalsplus.common.entity.util.abstracts.EntityAnimalWithTypes.func_184198_c(EntityAnimalWithTypes.java:30) ~[?:8.2.1.96]
> 	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1309) ~[?:?]
> 	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:302) ~[?:?]
> 	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:684) ~[?:?]
> 	at net.minecraft.world.server.ChunkManager.lambda$scheduleSave$10(ChunkManager.java:411) ~[?:?]
> 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_101]
> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_101]
> 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_101]
> 	at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:393) [?:?]
> 	at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:370) [?:?]
> 	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:342) [?:?]
> 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:313) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

I also have the animal net mod (to still be able to capture the animals for ease of traveling), and this issue does not appear with any of the animal nets. So I believe it is an issue with this mod's compatibility with BAP. 

EDIT: Do let me know if you need any further information to replicate.

**Comment by EvanRosenb01** [comment]
I also have the same problem. I am running a 1.14.4 server on forge version 28.2.0. While the log I am pasting in is from an error when placing down a Croc from the Croc Mod (https://www.curseforge.com/minecraft/mc-mods/crocmod) in the same fashion, doing the same with any entity from Better Animals Plus or Update Aquatic will crash the player and again remove the entity.

My log:

> [05Aug2020 11:36:33.474] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: GrimCreeper648 has made the advancement [Captured]
> [05Aug2020 11:37:19.953] [Netty Epoll Server IO #12/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
> [05Aug2020 11:37:19.954] [Netty Epoll Server IO #12/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
> [05Aug2020 11:37:19.995] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: GrimCreeper648 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
> [05Aug2020 11:37:19.996] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: GrimCreeper648 left the game
> [05Aug2020 11:37:27.582] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: There are 0 of a max 20 players online: 
> [05Aug2020 11:37:35.934] [User Authenticator #6/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player GrimCreeper648 is b3f6d96a-53df-4617-9185-e4e145dc56c4
> [05Aug2020 11:37:37.596] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: GrimCreeper648[/(IP ADDRESS)] logged in with entity id 41918 at (-3.0197561267039426, 73.0, -213.88362538742993)
> [05Aug2020 11:37:37.603] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: GrimCreeper648 joined the game
> [05Aug2020 11:37:37.645] [Netty Epoll Server IO #13/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.ModIdArgument@4377a0fd (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
> [05Aug2020 11:37:37.646] [Netty Epoll Server IO #13/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.EnumArgument@286d507 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
> [05Aug2020 11:37:37.681] [Netty Epoll Server IO #13/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
> [05Aug2020 11:37:37.681] [Netty Epoll Server IO #13/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
> [05Aug2020 11:37:37.686] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: GrimCreeper648 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
> [05Aug2020 11:37:37.687] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: GrimCreeper648 left the game
> [05Aug2020 11:38:16.321] [User Authenticator #7/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player GrimCreeper648 is b3f6d96a-53df-4617-9185-e4e145dc56c4
> [05Aug2020 11:38:17.995] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: GrimCreeper648[/(IP ADDRESS)] logged in with entity id 41924 at (-3.0197561267039426, 73.0, -213.88362538742993)
> [05Aug2020 11:38:18.005] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: GrimCreeper648 joined the game
> [05Aug2020 11:38:18.061] [Netty Epoll Server IO #14/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.ModIdArgument@4377a0fd (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
> [05Aug2020 11:38:18.062] [Netty Epoll Server IO #14/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.EnumArgument@286d507 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
> [05Aug2020 11:38:18.102] [Netty Epoll Server IO #14/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
> [05Aug2020 11:38:18.103] [Netty Epoll Server IO #14/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
> [05Aug2020 11:38:18.132] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: GrimCreeper648 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
> [05Aug2020 11:38:18.132] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: GrimCreeper648 left the game
> [05Aug2020 11:38:22.031] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: There are 0 of a max 20 players online: 
> [05Aug2020 11:39:10.979] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Saving the game (this may take a moment!)
> [05Aug2020 11:39:11.506] [Server thread/ERROR] [net.minecraft.world.chunk.storage.ChunkSerializer/]: An Entity type net.minecraft.entity.EntityType@465f159 has thrown an exception trying to write state. It will not persist. Report this to the mod author
> java.lang.NullPointerException: Null string not allowed
> 	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_211]
> 	at net.minecraft.nbt.StringNBT.<init>(StringNBT.java:18) ~[?:?]
> 	at net.minecraft.nbt.CompoundNBT.func_74778_a(CompoundNBT.java:117) ~[?:?]
> 	at its_meow.betteranimalsplus.common.entity.util.IVariantTypes.writeType(IVariantTypes.java:36) ~[?:9.0.1]
> 	at its_meow.betteranimalsplus.common.entity.util.abstracts.EntityAnimalWithTypes.func_184198_c(EntityAnimalWithTypes.java:30) ~[?:9.0.1]
> 	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1349) ~[?:?]
> 	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:319) ~[?:?]
> 	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:674) ~[?:?]
> 	at net.minecraft.world.server.ChunkManager.lambda$save$9(ChunkManager.java:349) ~[?:?]
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_211]
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_211]
> 	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_211]
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_211]
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211]
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211]
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_211]
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_211]
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_211]
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_211]
> 	at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:346) ~[?:?]
> 	at net.minecraft.world.server.ServerChunkProvider.func_217210_a(SourceFile:319) ~[?:?]
> 	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:746) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:513) ~[?:?]
> 	at net.minecraft.command.impl.SaveAllCommand.func_198614_a(SourceFile:34) ~[?:?]
> 	at net.minecraft.command.impl.SaveAllCommand.func_198610_b(SourceFile:20) ~[?:?]
> 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) [?:?]
> 	at net.minecraft.command.Commands.func_197059_a(Commands.java:194) [?:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:349) [?:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:325) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

My mod list is as follows:

> forge-1.14.4-28.2.0-server.jar Minecraft {minecraft@1.14.4 DONE}
> mcw-bridges-1.0.4-mc1.14.4.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
> useful_backpacks-1.14.4-1.7.6.60.jar Useful Backpacks {usefulbackpacks@1.7.6.60 DONE}
> QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
> crocmod-1.14.4-1.0.0-1.jar Crocodile Mod {crocmod@1.14.4-1.0.0-1 DONE}
> pandoras_creatures-1.14.4-0.13.1.jar Pandoras Creatures {pandoras_creatures@1.14.4-0.13.1 DONE}
> valhelsia_structures-14.0.4a.jar Valhelsia Structures {valhelsia_structures@14.0.4a DONE}
> bambooblocks-1.2.12.jar Bamboo Blocks {bambooblocks@1.2.11 DONE}
> jei-1.14.4-6.0.0.29.jar Just Enough Items {jei@6.0.0.29 DONE}
> fairylights-2.1.16-1.14.4.jar Fairy Lights {fairylights@2.1.16 DONE}
> mcw-windows-1.0.1-mc1.14.4.jar Macaw's Windows {mcwwindows@1.0.1 DONE}
> flower-breeding-1.4.jar Lizzie's Flower Breeding {acmc@1.0 DONE}
> Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
> 		gaiadimension-1.14.4-1.1.3.jar The Gaia Dimension {gaiadimension@1.1.3 DONE}
> 		Craftable Saddles [1.14]-1.3.jar Craftable Saddles {craftable_saddles@1.3 DONE}
> 		bloomful-1.2.4.jar Bloomful {bloomful@1.2.3 DONE}
> 		SpartanShields-1.14.4-2.0.0.jar Spartan Shields {spartanshields@2.0.0 DONE}
> 		flying_things-1.8.5-1.14.4.jar The Flying Things {flying_things@1.8.5 DONE}
> 		Waystones_1.14.4-5.1.1.jar Waystones {waystones@5.1.1 DONE}
> 		WallpaperCraft-1.14.4-1.0.6.jar Wallpapercraft {wallpapercraft@1.0.6 DONE}
> 		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
> 		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 DONE}
> 		placeableitems-4.1.1.jar Placeable Items {placeableitems@4.1.1 DONE}
> 		JRFTL [1.14.4]-1.1.jar JRFTL {jrftl@1.1 DONE}
> 		extlights-1.8.jar Extended Lights {extlights@1.8 DONE}
> 		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
> 		Elementary Staffs 1.3.2.jar Elementary Staffs {element@1.3.2 DONE}
> 		DoubleSlabs-1.14-1.7.5.jar Double Slabs {doubleslabs@1.7.5 DONE}
> 		betteranimalsplus-1.14.4-9.0.1.jar Better Animals Plus {betteranimalsplus@9.0.1 DONE}
> 		u_team_core-1.14.4-2.8.2.150.jar U Team Core {uteamcore@2.8.2.150 DONE}
> 		MoreVanillaArmor-Mod-1.14.4.jar MoreVanillaArmor {morevanillaarmor@1.0 DONE}
> 		TinyMobFarm-1.14.4-1.0.6.jar Tiny Mob Farm {tinymobfarm@1.0.5 DONE}
> 		mcw-roofs-1.0.2-mc1.14.4.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
> 		Apotheosis-1.14.4-2.4.4.jar Apotheosis {apotheosis@2.4.4 DONE}
> 		mcw-doors-1.0.0-mc1.14.4.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
> 		cfm-7.0.0-pre15-mc1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
> 		mcw-furniture-1.0.1-mc1.14.4.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
> 		PattysMoreArmor-Stable-1.14.4-1.5.jar pattysmorearmor {pattysmorearmor@1.5 DONE}
> 		mysticalwildlife-1.14.4-1.3.4.jar Mystical Wildlife {mysticalwildlife@1.3.4 DONE}
> 		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
> 		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
> 		cofh_core-1.14.4-0.4.0b.jar CoFH Core {cofh_core@0.4.0b DONE}
> 		Charm-1.14.4-1.5.7.jar Charm {charm@1.14.4-1.5.7 DONE}
> 		PattysMoreStuff-Stable-1.14.4-1.2.2.jar pattysmorestuff {pattysmorestuff@1.2.2 DONE}
> 		CosmeticArmorReworked-1.14.4-v3.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v3 DONE}
> 		SimpleDivingGear-3.0.4 mc 1.14.4.jar Simple Diving Gear {simpledivegear@3.0.4 mc 1.14.4 DONE}

**Comment by linxuanm** [comment]
This is on Better Animals' side. You should report to its author.

**Comment by SilentWolf101** [comment]
Very well. Thank you for your time.
