### ISSUE TITLE
Suggestion: Adding modded lootdrop

### ISSUE THREAD

**Issue by remplerus** [davidmaamoaix/TinyMobFarm#6]
Hey, I have found your mod and its really nice and helpful for my modpack. I only have 1 problem/suggestion. Is it possible to add drops from other mods like Lootbags or Essence from Mystical Agriculture?

TinyMobFarm Version: 1.12.2-1.0.5
Minecraft Version: 1.12.2
Forge Version: 1.12.2-14.23.5.2838

And if you need versions of those mods I want to add:
Lootbags Version: 1.12.2-2.5.8.5
Mystical Agriculture: 1.12.2-1.7.5

**Comment by linxuanm** [comment]
Mods like Lootbags add their custom drops to mobs via the entity death event (can't remember the name for that event). Tiny Mob Farm fetches the drops of mobs from their loot table, and therefore, cannot be easily integrated with mods that adds drops forcefully via entity deaths. I'm afraid I don't have time recently to look into integrating with such mods. Sorry.
