### ISSUE TITLE
Can't run it on a server

### ISSUE THREAD

**Issue by ItsClezz** [davidmaamoaix/TinyMobFarm#7]
8.07 13:09:05 [Multicraft] Starting server!
28.07 13:09:05 [Multicraft] Loaded config for "Forge 1.13.2"
28.07 13:09:05 [Multicraft] Updating eula.txt file
28.07 13:09:05 [Server] INFO OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
28.07 13:09:06 [Server] INFO 2019-07-28 13:09:06,262 main WARN Disabling terminal, you're running in an unsupported environment.
28.07 13:09:06 [Server] INFO [13:09:06.383] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 25.0.219, --fml.mcpVersion, 20190213.203750, --fml.mcVersion, 1.13.2, --fml.forgeGroup, net.minecraftforge, nogui]
28.07 13:09:06 [Server] INFO [13:09:06.401] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher starting: java version 1.8.0_201
28.07 13:09:06 [Server] INFO [13:09:06.603] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
28.07 13:09:07 [Server] INFO [13:09:07.143] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
28.07 13:09:17 [Server] INFO [13:09:17.614] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
28.07 13:09:17 [Server] INFO [13:09:17.615] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
28.07 13:09:17 [Server] INFO [13:09:17.616] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
28.07 13:09:17 [Server] INFO [13:09:17.617] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
28.07 13:09:17 [Server] INFO [13:09:17.618] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
28.07 13:09:17 [Server] INFO [13:09:17.766] [main/INFO] [minecraft/RecipeManager]: Loaded 0 recipes
28.07 13:09:17 [Server] INFO [13:09:17.768] [main/INFO] [minecraft/AdvancementList]: Loaded 0 advancements
28.07 13:09:17 [Server] INFO [13:09:17.774] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.13.2
28.07 13:09:17 [Server] INFO [13:09:17.813] [Server thread/INFO] [ne.mi.fm.ModLoader/CORE]: Loading Network data for FML net version: FML2
28.07 13:09:17 [Server] INFO [13:09:17.884] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/GuiScreen for invalid dist DEDICATED_SERVER
28.07 13:09:17 [Server] INFO [13:09:17.885] [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to load class cn.davidma.tinymobfarm.common.TinyMobFarm
28.07 13:09:17 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiScreen for invalid dist DEDICATED_SERVER
28.07 13:09:17 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge1132.jar:25.0] {}
28.07 13:09:17 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.lambda$offerClassNodeToPlugins$8(LaunchPluginHandler.java:41) ~[modlauncher-2.1.1.jar:?] {}
28.07 13:09:17 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:42) ~[modlauncher-2.1.1.jar:?] {}
28.07 13:09:17 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:96) ~[modlauncher-2.1.1.jar:?] {}
28.07 13:09:17 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:218) ~[modlauncher-2.1.1.jar:?] {}
28.07 13:09:17 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:109) ~[modlauncher-2.1.1.jar:?] {}
28.07 13:09:17 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:79) ~[modlauncher-2.1.1.jar:?] {}
28.07 13:09:17 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201] {}
28.07 13:09:17 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201] {}
28.07 13:09:18 [Multicraft] Server shut down (starting)
28.07 13:09:18 [Multicraft] Restarting crashed server in 1200 seconds
28.07 13:09:18 [Multicraft] Server stopped

**Comment by linxuanm** [comment]
Fixed.
